joint_limits:
  jaco_joint_1:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 0.83775804095
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_2:
    has_position_limits: true
    min_position: -3.89208423195
    max_position: 0.75049157835
    has_velocity_limits: true
    max_velocity: 0.83775804095
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_3:
    has_position_limits: true
    min_position: -4.38077642251
    max_position: 1.23918376892
    has_velocity_limits: true
    max_velocity: 0.83775804095
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_4:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 1.0471975512
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_5:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 1.0471975512
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_6:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 1.0471975512
    has_acceleration_limits: false
    max_acceleration: 0.6
  jaco_joint_finger_1:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  jaco_joint_finger_2:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  jaco_joint_finger_3:
    has_velocity_limits: false
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
